site_name: Analiza danych w Transporcie

nav:

  - Kurs: 0-WorkshopDescription/course_description.md
  - Lakehouse:
    - 1.Lakehouse: 1-Lakehouse/1_1_lakehouse.md
    - 2.Medallion Architecture: 1-Lakehouse/1_0_medallion_architecture.md
    - 3.Delta Lake: 1-Lakehouse/1_2_delta_lake.md
    - 4.Spark: 1-Lakehouse/1_3_spark.md
    - 5.Project: 1-Lakehouse/1_4_project.md
  - Databricks:
      - 1.Architecture: 2-Databricks/db_platform_architecture.md
      - Lab Python Data Types: 2-Databricks/python_data_types1.ipynb
      - 2.Core parts: empty.md
      - 3.Notebooks: empty.md
  - "<i class='fas fa-lock'></i>  Delta Lake" :
      - 1.Introduction: 3-DeltaLake/1_0_delta_lake_introduction.md
      - 2.Files processing: 3-DeltaLake/1_1_processing_files.md
      - 3.Incremental loading: 3-DeltaLake/1_2_incremental_loading.md
      - 4.Table types: 3-DeltaLake/1_3_managed_external_tables.md

  - "<i class='fas fa-lock'></i>  Spark":
      - 1.Introduction: 4-Spark/architecture.md
      - Functions:
          - dates: 4-Spark/dates.md
          - window functions: 4-Spark/window_functions.md

  - "<i class='fas fa-lock'></i>  Labs":
      - Day 1:
        - Summary: Labs/Day1/day1.md
        - Lab 1:
          - Python Data Types: Labs/Day1/python_data_types.md
          - Lab Python Data Types1: Labs/Day1/python_data_types1.ipynb
          - Lab Python Data Types: Labs/Day1/python_data_types1.md
      - Day 2:
        - Summary: Labs/Day2/day2.md
      - Day 3:
        - Summary: Labs/Day3/day3.md



#Fonts https://fontawesome.com/v4/icons/#payment
theme:
  icon:
    repo: fontawesome/brands/gitlab
  name: material #eg. readthedocs
  logo: assets/iclogo.png
  features:
    - content.code.copy
    - content.tooltips
    - toc.follow
    - toc.integrate #no right toc
    - navigation.top
    - navigation.path #breadcumbs alll integrated on the left side
    - content.code.select
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand #default expand left menu
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: teal
      accent: purple

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: teal
      accent: lime


markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - tables
  - admonition
  - pymdownx.details

  - pymdownx.emoji
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  - pymdownx.highlight:
      pygments_lang_class: true
      anchor_linenums: true
      auto_title: true
      line_spans: __span
      linenums: true

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - tables

plugins:
  - search
  - mkdocs-jupyter:
      include: [ "*.ipynb" ] # Default: ["*.py", "*.ipynb"]
      #- ignore: [ "some-irrelevant-files/*.ipynb" ]
      include_source: True
      include_requirejs: true #For plotly
  - glightbox:
     zoomable: true
     touchNavigation: true
     slide_effect: slide
     draggable: true
     skip_classes:
      - skip-lightbox
  - slides

  - encryptcontent:
      title_prefix: ''
      summary: 'This content is locked for lab users'
      password_button_text: 'ENTER'
      password_button: True

      password_inventory:
        classified: 'labs2025'
      reload_scripts:
      - '#init-glightbox'

#SOCIAL MEDIA
#extra:
#  social:
#    - icon: fontawesome/solid/lock
#      link: 1_Lakehouse/1_1_lakehouse.md
#      name: Restricted Section

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
copyright: |
  &copy; 2025 Krzysztof Modelewski
  
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css
  

