site_name: Transportation Data Analysis course

nav:
  - Lakehouse:
    - "<i class='fas fa-lock'></i> 1.Lakehouse": 1-Lakehouse/1_1_lakehouse.md
    - 2.Medalion Architecture: 1_Lakehouse/1_0_medallion_architecture.md
    - 3.Delta Lake: 1-Lakehouse/1_2_delta_lake.md
  - Databricks:
      - 1.Architecture: 2-Databricks/db_platform_architecture.md
      - 2.Core parts: empty.md
      - 3.Notebooks: empty.md
  - DeltaLake:
      - 1.Introduction: 3-DeltaLake/1_0_delta_lake_introduction.md
      - 2.Files processing: 3-DeltaLake/1_1_processing_files.md
      - 3.Incremental loading: 3-DeltaLake/1_2_incremental_loading.md
      - 4.Table types: 3-DeltaLake/1_3_managed_external_tables.md

#Fonts https://fontawesome.com/v4/icons/#payment
theme:
  icon:
    repo: fontawesome/brands/gitlab
  name: material #eg. readthedocs
  logo: assets/iclogo.png
  features:
    - content.code.copy
    - content.tooltips
    - toc.follow
    - toc.integrate #no right toc
    - navigation.top
    - navigation.path #breadcumbs alll integrated on the left side
    - content.code.select
    - content.code.annotate
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand #default expand left menu
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: teal
      accent: purple

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: teal
      accent: lime


markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - tables
  - admonition
  - pymdownx.details

  - pymdownx.emoji
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  - pymdownx.highlight:
      pygments_lang_class: true
      anchor_linenums: true
      auto_title: true
      line_spans: __span
      linenums: true

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - tables

plugins:
  - glightbox:
     zoomable: true
     draggable: true
     skip_classes:
      - skip-lightbox

  - encryptcontent:
      title_prefix: ''
      summary: 'This content is locked for lab users'
      password_button_text: 'ENTER'
      password_button: True

      password_inventory:
        classified: 'labs2025'
      reload_scripts:
      - '#init-glightbox'

#SOCIAL MEDIA
#extra:
#  social:
#    - icon: fontawesome/solid/lock
#      link: 1_Lakehouse/1_1_lakehouse.md
#      name: Restricted Section

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
copyright: |
  &copy; 2025 Krzysztof Modelewski
  
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css
  

